name: Java Maven Build & Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 19
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Build project
        run: mvn clean package

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: DiplomovaPraca-jar
          path: target/DiplomovaPraca-1.0-SNAPSHOT.jar
